### ISSUE TITLE
PHP Warnings when running WPCLI

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/pmpro-add-member-admin#39] opened 2020-10-19 06:20 UTC
Error: Warning: array_merge(): Argument #1 is not an array in /home/earthera/public_html/wp-content/plugins/pmpro-add-member-admin/pmpro-add-member-admin.php on line 132

Plugin Versions: 

- PMPRO 2.2.4
- WP 5.5.1
- PHP 7.4
- PMPro – Add Member from Admin v .6
- PMPro – Level Cost Text v .3.2
- PMPro – Sitewide Sales v 1.2.5

Related to this topic: https://www.paidmembershipspro.com/forums/topic/wpcli-error-messages/

**Comment by dparker1005** [comment] 2020-10-19 15:42
Duplicate of https://github.com/strangerstudios/pmpro-add-member-admin/issues/39.

**Closed by dparker1005** 2020-10-19 15:42 UTC
