### ISSUE TITLE
Error log: conflict with Jetpack

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-add-member-admin#33] opened 2020-03-25 13:17 UTC
[08-Jan-2020 15:08:17 UTC] PHP Warning: array_merge(): Argument #1 is not an array in /home/veldarch/public_html/OntarioBarnPreservation.com/wp-content/plugins/pmpro-add-member-admin/pmpro-add-member-admin.php on line 132 [08-Jan-2020 15:08:17 UTC] PHP Warning: array_filter() expects parameter 1 to be array, null given in /home/veldarch/public_html/OntarioBarnPreservation.com/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/modules/class-callables.php on line 325

**Comment by dparker1005** [comment] 2020-08-13 17:57
Duplicate of #24

**Closed by dparker1005** 2020-08-13 17:57 UTC
