### ISSUE TITLE
Send a customised email to newly added members

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-add-member-admin#28] opened 2019-09-10 18:09 UTC
https://www.paidmembershipspro.com/forums/topic/customizing-email-for-add-member-via-admin-add-on/

Users get the default WordPress email, there should be a template for users added with Add Member add on

**Comment by kimwhite** [comment] 2020-07-20 18:08
Ditto. What Femi said.

**Comment by dparker1005** [comment] 2020-08-13 17:56
Duplicate of #31

**Closed by dparker1005** 2020-08-13 17:56 UTC
